@URL = {{baseUrl}}/categories
### Get Categories
GET {{URL}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Categoty by Id
GET {{URL}}/2e9e23f6-8a6f-4a7c-9c40-af1e3f4d31b4
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Create
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Somethings",
    "description": "Somethings"
}
